name: CI/CD Pipeline
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: friendy21
  IMAGE_NAME: cicd-nomad-app
  NODE_VERSION: '18'

jobs:
  # Build and test job
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}

  # Deploy to production
  deploy-production:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.MANAGEMENT_SERVER_IP }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Deploy to Nomad via Management Server
        env:
          IMAGE_TAG: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        run: |
          # Copy Nomad job file to management server
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            nomad/app.nomad \
            root@${{ secrets.MANAGEMENT_SERVER_IP }}:/tmp/app.nomad
          
          # Deploy using Nomad with ACL token
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            root@${{ secrets.MANAGEMENT_SERVER_IP }} << 'ENDSSH'
          set -e
          
          # Export Nomad configuration
          export NOMAD_TOKEN="${{ secrets.NOMAD_TOKEN }}"
          export NOMAD_ADDR="http://127.0.0.1:4646"
          
          # Update image in job file
          sed -i "s|REPLACE_IMAGE|${{ env.IMAGE_TAG }}|g" /tmp/app.nomad
          
          # Validate and run the job
          echo "Validating job specification..."
          nomad job validate /tmp/app.nomad
          
          echo "Running Nomad job..."
          nomad job run -check-index 0 /tmp/app.nomad
          
          # Wait for deployment
          sleep 10
          
          # Check deployment status
          nomad job status app
          ENDSSH

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            root@${{ secrets.MANAGEMENT_SERVER_IP }} << 'ENDSSH'
          # Check if service is running
          nomad job status app | grep -q "running" && echo "✓ Deployment successful" || echo "✗ Deployment may have issues"
          ENDSSH

      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/deploy_key
