name: ci-cd-nomad
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/cicd-nomad-app
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Package Nomad job
        run: |
          mkdir -p artifacts
          cp nomad/jobs/app.nomad artifacts/app.nomad

      - name: Copy Nomad job to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          source: "artifacts/app.nomad"
          target: "/root/ci/"

      - name: Deploy on Nomad
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            set -e
            IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/cicd-nomad-app:latest"
            sed -i "s|REPLACE_IMAGE|$IMAGE|g" /root/ci/artifacts/app.nomad
            nomad job run -detach /root/ci/artifacts/app.nomad
