# .github/workflows/main.yml
name: CI/CD Pipeline
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: friendy21
  IMAGE_NAME: cicd-nomad-app
  NODE_VERSION: '18'

jobs:
  # Build and test job
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          # Remove npm cache to avoid corruption issues
          cache: ''

      - name: Clear npm cache and install dependencies
        run: |
          # Clear npm cache to fix integrity issues
          npm cache clean --force
          
          # Remove package-lock.json to regenerate it
          rm -f package-lock.json
          
          # Remove node_modules if exists
          rm -rf node_modules
          
          # Set npm registry explicitly
          npm config set registry https://registry.npmjs.org/
          
          # Install dependencies with fresh package-lock.json
          npm install --verbose
          
          # Alternative: If npm install fails, try with --force
          # npm install --force --verbose

      - name: Run tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}

  # Deploy to production
  deploy-production:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Nomad via Management Server
        env:
          IMAGE_TAG: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        run: |
          # Decode SSH key
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" | base64 -d > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          
          # Add server to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.MANAGEMENT_SERVER_IP }} >> ~/.ssh/known_hosts 2>/dev/null || true
          
          # Copy Nomad job file
          scp -i /tmp/deploy_key -o StrictHostKeyChecking=no \
            nomad/app.nomad \
            root@${{ secrets.MANAGEMENT_SERVER_IP }}:/tmp/app.nomad
          
          # Deploy using Nomad
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no \
            root@${{ secrets.MANAGEMENT_SERVER_IP }} << 'ENDSSH'
          set -e
          
          # Export Nomad configuration
          export NOMAD_TOKEN="${{ secrets.NOMAD_TOKEN }}"
          export NOMAD_ADDR="http://127.0.0.1:4646"
          
          # Update image in job file
          IMAGE="${{ env.IMAGE_TAG }}"
          sed -i "s|REPLACE_IMAGE|$IMAGE|g" /tmp/app.nomad
          
          # Validate and run the job
          echo "Validating job specification..."
          nomad job validate /tmp/app.nomad || true
          
          echo "Running Nomad job..."
          nomad job run -check-index 0 /tmp/app.nomad
          
          # Wait for deployment
          sleep 10
          
          # Check job status
          nomad job status app || true
          ENDSSH
          
          # Cleanup
          rm -f /tmp/deploy_key

      - name: Verify deployment
        run: |
          echo "Deployment completed successfully"
